/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceiverRouteImport } from './routes/receiver'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiverIndexRouteImport } from './routes/receiver.index'
import { Route as ProviderIndexRouteImport } from './routes/provider.index'
import { Route as ProviderRequestsRouteImport } from './routes/provider.requests'
import { Route as ProviderPostsRouteImport } from './routes/provider.posts'
import { Route as ProviderEsgRouteImport } from './routes/provider.esg'
import { Route as ProviderCreateRouteImport } from './routes/provider.create'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'

const ReceiverRoute = ReceiverRouteImport.update({
  id: '/receiver',
  path: '/receiver',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiverIndexRoute = ReceiverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReceiverRoute,
} as any)
const ProviderIndexRoute = ProviderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderRequestsRoute = ProviderRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderPostsRoute = ProviderPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderEsgRoute = ProviderEsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderCreateRoute = ProviderCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ProviderRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/provider': typeof ProviderRouteWithChildren
  '/receiver': typeof ReceiverRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/provider/create': typeof ProviderCreateRoute
  '/provider/esg': typeof ProviderEsgRoute
  '/provider/posts': typeof ProviderPostsRoute
  '/provider/requests': typeof ProviderRequestsRoute
  '/provider/': typeof ProviderIndexRoute
  '/receiver/': typeof ReceiverIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/provider/create': typeof ProviderCreateRoute
  '/provider/esg': typeof ProviderEsgRoute
  '/provider/posts': typeof ProviderPostsRoute
  '/provider/requests': typeof ProviderRequestsRoute
  '/provider': typeof ProviderIndexRoute
  '/receiver': typeof ReceiverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/provider': typeof ProviderRouteWithChildren
  '/receiver': typeof ReceiverRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/provider/create': typeof ProviderCreateRoute
  '/provider/esg': typeof ProviderEsgRoute
  '/provider/posts': typeof ProviderPostsRoute
  '/provider/requests': typeof ProviderRequestsRoute
  '/provider/': typeof ProviderIndexRoute
  '/receiver/': typeof ReceiverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/provider'
    | '/receiver'
    | '/auth/login'
    | '/auth/register'
    | '/provider/create'
    | '/provider/esg'
    | '/provider/posts'
    | '/provider/requests'
    | '/provider/'
    | '/receiver/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/provider/create'
    | '/provider/esg'
    | '/provider/posts'
    | '/provider/requests'
    | '/provider'
    | '/receiver'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/provider'
    | '/receiver'
    | '/auth/login'
    | '/auth/register'
    | '/provider/create'
    | '/provider/esg'
    | '/provider/posts'
    | '/provider/requests'
    | '/provider/'
    | '/receiver/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProviderRoute: typeof ProviderRouteWithChildren
  ReceiverRoute: typeof ReceiverRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receiver': {
      id: '/receiver'
      path: '/receiver'
      fullPath: '/receiver'
      preLoaderRoute: typeof ReceiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receiver/': {
      id: '/receiver/'
      path: '/'
      fullPath: '/receiver/'
      preLoaderRoute: typeof ReceiverIndexRouteImport
      parentRoute: typeof ReceiverRoute
    }
    '/provider/': {
      id: '/provider/'
      path: '/'
      fullPath: '/provider/'
      preLoaderRoute: typeof ProviderIndexRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/requests': {
      id: '/provider/requests'
      path: '/requests'
      fullPath: '/provider/requests'
      preLoaderRoute: typeof ProviderRequestsRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/posts': {
      id: '/provider/posts'
      path: '/posts'
      fullPath: '/provider/posts'
      preLoaderRoute: typeof ProviderPostsRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/esg': {
      id: '/provider/esg'
      path: '/esg'
      fullPath: '/provider/esg'
      preLoaderRoute: typeof ProviderEsgRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/create': {
      id: '/provider/create'
      path: '/create'
      fullPath: '/provider/create'
      preLoaderRoute: typeof ProviderCreateRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProviderRouteChildren {
  ProviderCreateRoute: typeof ProviderCreateRoute
  ProviderEsgRoute: typeof ProviderEsgRoute
  ProviderPostsRoute: typeof ProviderPostsRoute
  ProviderRequestsRoute: typeof ProviderRequestsRoute
  ProviderIndexRoute: typeof ProviderIndexRoute
}

const ProviderRouteChildren: ProviderRouteChildren = {
  ProviderCreateRoute: ProviderCreateRoute,
  ProviderEsgRoute: ProviderEsgRoute,
  ProviderPostsRoute: ProviderPostsRoute,
  ProviderRequestsRoute: ProviderRequestsRoute,
  ProviderIndexRoute: ProviderIndexRoute,
}

const ProviderRouteWithChildren = ProviderRoute._addFileChildren(
  ProviderRouteChildren,
)

interface ReceiverRouteChildren {
  ReceiverIndexRoute: typeof ReceiverIndexRoute
}

const ReceiverRouteChildren: ReceiverRouteChildren = {
  ReceiverIndexRoute: ReceiverIndexRoute,
}

const ReceiverRouteWithChildren = ReceiverRoute._addFileChildren(
  ReceiverRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProviderRoute: ProviderRouteWithChildren,
  ReceiverRoute: ReceiverRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
